" Plugins
call plug#begin('~/.vim/plugged')
Plug 'tpope/vim-commentary' " 'gc' for commenting
Plug 'tpope/vim-surround'
Plug 'lervag/vimtex' " tex/latex/contex
Plug 'vim-scripts/DoxygenToolkit.vim' " :Dox for C++
Plug 'Chiel92/vim-autoformat' " autoformatting different file formats
Plug 'jacoborus/tender.vim' " tender color scheme
call plug#end()

" Basic
set lazyredraw
set ttyfast
set splitbelow splitright
set clipboard=unnamedplus
set encoding=utf-8

" UI
syntax enable
set number
set relativenumber
set showcmd

" Colors
set termguicolors " enable 24-bit colors
set t_8f=[38;2;%lu;%lu;%lum " set foreground color
set t_8b=[48;2;%lu;%lu;%lum " set background color
colorscheme tender
highlight Normal guibg=NONE
highlight Visual guibg=#303030

" Search
set ignorecase
set smartcase
set incsearch

" Indent / cursor behavior
set autoindent
set nostartofline
set scrolloff=2

" Undo
set undofile
set undodir=~/.vim/undodir

" Autoformat
autocmd BufWrite * :Autoformat
let g:autoformat_autoindent = 0
let g:autoformat_retab = 0

" Termdebug
packadd termdebug

" Filetype specific
filetype plugin on
autocmd FileType html,css,tex,latex,context setlocal tabstop=2

" No arrow keys
noremap <Up> <Nop>
inoremap <Up> <Nop>
noremap <Down> <Nop>
inoremap <Down> <Nop>
noremap <Left> <Nop>
inoremap <Left> <Nop>
noremap <Right> <Nop>
inoremap <Right> <Nop>
