" Plugins
packadd! matchit
runtime ftplugin/man.vim

call plug#begin('~/.vim/plugged')
Plug 'tpope/vim-commentary'
Plug 'tpope/vim-surround'
Plug 'lervag/vimtex'
Plug 'vim-scripts/DoxygenToolkit.vim', { 'for' : 'cpp' }
Plug 'aonemd/kuroi.vim'
let g:plug_shallow = 0
" Repositories not supporting shallow clone
Plug 'https://sanctum.geek.nz/code/vim-redact-pass.git'
call plug#end()

" Basic
filetype plugin indent on
syntax enable
set hidden
set splitbelow splitright
set history=1000
set nrformats-=octal

" Input, drawing
set lazyredraw
set ttyfast
set ttimeout
set ttimeoutlen=100

" Clipboard
set clipboard^=unnamedplus

" UI
set number
set relativenumber
set showcmd
set ruler
set wildmenu
set display+=lastline
set listchars=tab:>\ ,trail:-,extends:>,precedes:<,nbsp:+

" Search
set ignorecase
set smartcase
set incsearch

" Cursor behavior
set autoindent
set backspace=indent,eol,start
set formatoptions+=j
set smarttab
set nostartofline
set scrolloff=2

" Undo, Swap
set undofile
set undodir=~/.vim/undo//
set directory=~/.vim/swap//

" Colors
set termguicolors " enable 24-bit colors
set t_8f=[38;2;%lu;%lu;%lum " set foreground color
set t_8b=[48;2;%lu;%lu;%lum " set background color

" Colorscheme
set background=dark
colorscheme kuroi
highlight Normal guibg=NONE
highlight EndOfBuffer cterm=NONE gui=NONE guibg=NONE

" Delete trailing whitespace on save
autocmd BufWrite * %s/\s\+$//e

" Filetype specific
autocmd FileType html,css,tex,latex,context setlocal tabstop=2

augroup filetypedetect
	autocmd BufRead,BufNewFile *aerc*.eml setfiletype mail
augroup END
