user_pref("extensions.pocket.enabled", false);
user_pref("reader.parse-on-load.enabled", false);
user_pref("browser.bookmarks.openInTabClosesMenu", false);
user_pref("browser.search.context.loadInBackground", true);
user_pref("browser.tabs.loadBookmarksInBackground", true);
user_pref("view_source.editor.external", true);
user_pref("view_source.editor.path", "vim");
user_pref("browser.fullscreen.autohide", false);
user_pref("geo.enabled", false);
user_pref("layout.word_select.eat_space_to_next_word", true);
//potential problems
user_pref("dom.event.clipboardevents.enabled", false);
user_pref("findbar.highlightAll", true);
user_pref("network.IDN_show_punycode", true);
user_pref("browser.tabs.insertAfterCurrent", true);
user_pref("browser.tabs.closeWindowWithLastTab", true);
user_pref("toolkit.cosmeticAnimations.enabled", false);
user_pref("full-screen-api.transition-duration.enter", "0 0");
user_pref("full-screen-api.transition-duration.leave", "0 0");
user_pref("devPixelsPerPx", "1.0");
