#!/bin/sh

xsetroot -cursor_name left_ptr &
SXHKD_SHELL=sh sxhkd -m 1 &
polybar top &
feh --bg-scale --no-fehbg "$HOME/.wallpaper" &
redshift &
"$BROWSER" &

bspc monitor -d 1 2 3 4 5

bspc config border_width          1
bspc config window_gap            0
bspc config presel_feedback_color '#202020'

bspc config automatic_mode       alternate

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config single_monocle       true
bspc config ignore_ewmh_focus    true

bspc rule -a Pinentry-gtk-2 state=floating
bspc rule -a Zathura state=tiled
bspc rule -a Emacs state=tiled
bspc rule -a Surf state=tiled
bspc rule -a imv state=tiled
